### ISSUE TITLE
There is no code to make a figure from RT-qPCR data.

### ISSUE THREAD

**Issue by davidbrown2324** [HuangLabPopulation/RT-qPCR#2]
We need some code to 
1. Import RT-qPCR data
2. Organise it into a pandas DataFrame
3. Perform the appropriate normalization
4. Generate publishable figures

Would anyone in the @HuangLabPopulation/dna-probes team like to help with this?

**Comment by shuqin19** [comment]
I should add to help with generate python code to Import and Analyze data

**Comment by davidbrown2324** [comment]
@shuqin19 Great idea. The best way to do that would be
1. Fork this repository to your account
2. Upload your code
3. Make a pull request explaining what you are adding

I will review your pull request (check your code) and then integrate it with this master repo

**Comment by shuqin19** [comment]
Please see the new pull request, I added a script for data processing

**Comment by davidbrown2324** [comment]
You can reference a pull request using the # symbol or clicking the star bookmark icon above the comment window. This #3 should referenc your pull request.
